"""
VAE Reconstruction Error AI Detection Module

Inspired by DIRE (ICCV 2023) and CO-SPY (CVPR 2025).

Core insight: Images generated by diffusion models (Stable Diffusion,
DALL-E, Midjourney) lie on the learned manifold of the VAE used during
generation. When you encode→decode such an image through the same or
similar VAE, the reconstruction error is LOW because the image is
"native" to the latent space.

Real photographs, conversely, exist OUTSIDE this manifold. Passing them
through a VAE produces significant reconstruction error because the VAE
cannot faithfully represent all the detail and noise present in a real
photograph.

Detection approach:
1. Load the Stable Diffusion VAE (sd-vae-ft-mse, ~300 MB).
2. Encode the input image into latent space (4×H/8×W/8).
3. Decode the latent back to pixel space.
4. Compute the absolute reconstruction error map.
5. Derive statistics: mean error, std, spatial uniformity, high-freq loss.
6. Low mean error + high uniformity → AI-generated.
"""

import io
import logging
import os
import time

import numpy as np
from PIL import Image

from ...config import settings
from ..base import AnalyzerFinding, BaseAnalyzer, ModuleResult

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Lazy imports
# ---------------------------------------------------------------------------
_TORCH_AVAILABLE = False

try:
    import torch
    _TORCH_AVAILABLE = True
except ImportError:
    pass

_VAE_MODEL_ID = "stabilityai/sd-vae-ft-mse"

# Lazy-loaded VGG16 feature extractor for LPIPS-style perceptual distance
_vgg_features = None


def _get_vgg_features():
    """Lazy-load VGG16 feature extractor (first 16 layers = through relu3_3)."""
    global _vgg_features
    if _vgg_features is None:
        try:
            from torchvision.models import vgg16, VGG16_Weights
            model = vgg16(weights=VGG16_Weights.DEFAULT)
            device = "cuda" if torch.cuda.is_available() else "cpu"
            _vgg_features = torch.nn.Sequential(*list(model.features[:16])).to(device)
            _vgg_features.eval()
            for p in _vgg_features.parameters():
                p.requires_grad = False
            logger.info("VGG16 feature extractor loaded on %s for LPIPS", device)
        except Exception as e:
            logger.warning("Failed to load VGG16 for LPIPS: %s", e)
    return _vgg_features

# Thresholds derived from empirical testing:
# Real images: mean_error ~0.06-0.12, uniformity ~0.3-0.6
# AI images:   mean_error ~0.02-0.05, uniformity ~0.6-0.9
_THRESH_DETECTED = 0.035       # Very low error → almost certainly AI
_THRESH_SUSPECTED = 0.055      # Moderately low error → suspicious
_THRESH_LOW = 0.075            # Slightly low error → weak indicator
_UNIFORMITY_BOOST = 0.65       # High uniformity amplifies the signal


class VaeReconstructionAnalyzer(BaseAnalyzer):
    """VAE reconstruction error analysis for AI image detection."""

    MODULE_NAME = "vae_reconstruction"
    MODULE_LABEL = "VAE rekonstrukcija"

    def __init__(self) -> None:
        self._models_loaded = False
        self._vae = None

    # ------------------------------------------------------------------
    # Model loading
    # ------------------------------------------------------------------

    def _ensure_models(self) -> None:
        if self._models_loaded:
            return

        if not _TORCH_AVAILABLE:
            self._models_loaded = True
            return

        if not getattr(settings, "forensics_vae_recon_enabled", True):
            self._models_loaded = True
            return

        try:
            from diffusers import AutoencoderKL

            cache_dir = os.path.join(settings.forensics_model_cache_dir, "vae_recon")
            os.makedirs(cache_dir, exist_ok=True)

            model_id = getattr(settings, "forensics_vae_recon_model", _VAE_MODEL_ID)
            self._device = "cuda" if torch.cuda.is_available() else "cpu"
            self._vae = AutoencoderKL.from_pretrained(
                model_id, cache_dir=cache_dir
            ).to(self._device)
            self._vae.eval()
            logger.info("VAE reconstruction model loaded on %s: %s", self._device, model_id)
        except Exception as e:
            logger.warning("Failed to load VAE model: %s", e)
            self._vae = None

        self._models_loaded = True

    # ------------------------------------------------------------------
    # Analysis
    # ------------------------------------------------------------------

    async def analyze_image(self, image_bytes: bytes, filename: str) -> ModuleResult:
        start = time.monotonic()
        findings: list[AnalyzerFinding] = []

        if not getattr(settings, "forensics_vae_recon_enabled", True):
            return self._make_result([], int((time.monotonic() - start) * 1000))

        try:
            self._ensure_models()

            if self._vae is None:
                return self._make_result(
                    [], int((time.monotonic() - start) * 1000),
                    error="VAE model not available (diffusers not installed?)"
                )

            img = Image.open(io.BytesIO(image_bytes))
            if img.mode != "RGB":
                img = img.convert("RGB")

            stats = self._compute_reconstruction_error(img)
            self._emit_findings(stats, findings)

        except Exception as e:
            logger.warning("VAE reconstruction error: %s", e)
            return self._make_result(
                [], int((time.monotonic() - start) * 1000), error=str(e)
            )

        elapsed = int((time.monotonic() - start) * 1000)
        return self._make_result(findings, elapsed)

    async def analyze_document(self, doc_bytes: bytes, filename: str) -> ModuleResult:
        return self._make_result([], 0)

    # ------------------------------------------------------------------
    # Core computation
    # ------------------------------------------------------------------

    def _compute_reconstruction_error(self, img: Image.Image) -> dict:
        """
        Encode→decode through VAE and compute reconstruction error stats.

        Returns dict with:
          mean_error, std_error, percentile_95, spatial_uniformity,
          high_freq_loss, ai_probability
        """
        # Resize to VAE-compatible dimensions (multiples of 8, max 512)
        w, h = img.size
        target_size = 512
        scale = min(target_size / w, target_size / h, 1.0)
        new_w = int(w * scale) // 8 * 8
        new_h = int(h * scale) // 8 * 8
        new_w = max(new_w, 8)
        new_h = max(new_h, 8)
        img_resized = img.resize((new_w, new_h), Image.LANCZOS)

        # Convert to tensor on correct device: [0, 1] → [-1, 1]
        device = getattr(self, "_device", "cpu")
        arr = np.array(img_resized, dtype=np.float32) / 255.0
        tensor = torch.from_numpy(arr).permute(2, 0, 1).unsqueeze(0).to(device)
        tensor = tensor * 2.0 - 1.0  # [-1, 1]

        # Encode → latent → decode
        with torch.no_grad():
            latent = self._vae.encode(tensor).latent_dist.mean
            reconstructed = self._vae.decode(latent).sample

        # Back to [0, 1]
        original_01 = (tensor + 1.0) / 2.0
        recon_01 = (reconstructed + 1.0) / 2.0
        recon_01 = recon_01.clamp(0.0, 1.0)

        # Error map
        error_map = torch.abs(original_01 - recon_01).squeeze(0)  # (3, H, W)
        error_np = error_map.cpu().numpy()

        # Global statistics
        mean_error = float(error_np.mean())
        std_error = float(error_np.std())
        p95 = float(np.percentile(error_np, 95))

        # Spatial uniformity: how evenly distributed is the error?
        # Low std/mean ratio = uniform (AI), High ratio = concentrated (real edits)
        per_pixel_error = error_np.mean(axis=0)  # (H, W) — average across channels
        block_size = max(new_h // 8, 1)
        blocks = []
        for i in range(0, per_pixel_error.shape[0] - block_size + 1, block_size):
            for j in range(0, per_pixel_error.shape[1] - block_size + 1, block_size):
                block = per_pixel_error[i:i + block_size, j:j + block_size]
                blocks.append(float(block.mean()))
        if blocks and np.mean(blocks) > 1e-8:
            block_mean = np.mean(blocks)
            block_std = np.std(blocks)
            spatial_uniformity = 1.0 - min(1.0, block_std / (block_mean + 1e-8))
        else:
            spatial_uniformity = 0.5

        # High-frequency loss: compare Laplacian of original vs reconstructed
        orig_gray = original_01.squeeze(0).mean(dim=0).cpu().numpy()
        recon_gray = recon_01.squeeze(0).mean(dim=0).cpu().numpy()
        lap_orig = self._laplacian_energy(orig_gray)
        lap_recon = self._laplacian_energy(recon_gray)
        if lap_orig > 1e-8:
            high_freq_loss = 1.0 - min(1.0, lap_recon / lap_orig)
        else:
            high_freq_loss = 0.0

        # ── FFT error frequency analysis ──────────────────────────────
        error_gray = per_pixel_error  # already (H, W)
        fft_energy = self._compute_fft_error_energy(error_gray)

        # ── LPIPS and SSIM for base reconstruction ────────────────────
        lpips_distance = self._compute_lpips(original_01, recon_01)
        ssim_value = self._compute_ssim(orig_gray, recon_gray)

        # Compute AI probability from error statistics (now with FFT)
        ai_prob = self._error_to_probability(
            mean_error, spatial_uniformity, high_freq_loss,
            fft_mid=fft_energy["mid"],
        )

        # ── Multi-noise snap-back analysis ────────────────────────────
        # Add noise at multiple levels, re-encode->decode, measure how
        # quickly the image "snaps back" to the VAE manifold.
        # AI images snap back faster (lower distance).
        snap_back = self._multi_noise_snap_back(tensor)
        ai_prob_snapback = snap_back.get("snap_back_score", 0.0)

        # Combine: snap-back with LPIPS is more reliable, give it more weight
        combined_prob = ai_prob * 0.40 + ai_prob_snapback * 0.60

        return {
            "mean_error": round(mean_error, 6),
            "std_error": round(std_error, 6),
            "percentile_95": round(p95, 6),
            "spatial_uniformity": round(spatial_uniformity, 4),
            "high_freq_loss": round(high_freq_loss, 4),
            "fft_energy": {k: round(v, 4) for k, v in fft_energy.items()},
            "lpips_distance": round(lpips_distance, 6),
            "ssim": round(ssim_value, 4),
            "ai_probability": round(combined_prob, 4),
            "snap_back_score": round(ai_prob_snapback, 4),
            "snap_back_coefficients": snap_back.get("coefficients", []),
            "snap_back_metrics": snap_back.get("per_level_metrics", []),
        }

    def _multi_noise_snap_back(self, original_tensor: torch.Tensor) -> dict:
        """Multi-noise snap-back analysis (Diffusion Snap-Back).

        For each noise level sigma:
          1. Add Gaussian noise to the image
          2. Encode->decode through VAE
          3. Measure distance from reconstructed to ORIGINAL (not noisy)
          4. AI images snap back to original faster (lower distance)

        Uses three complementary metrics:
          - MAE: pixel-level reconstruction accuracy
          - LPIPS: perceptual similarity (most discriminative)
          - SSIM: structural similarity improvement

        The snap-back coefficient = 1 - (recon_dist / noisy_dist).
        High coefficient = fast snap-back = likely AI.
        """
        noise_levels = [0.01, 0.03, 0.06, 0.10, 0.15, 0.20]
        # Weights per noise level: higher noise = more informative
        level_weights = [0.05, 0.10, 0.15, 0.20, 0.25, 0.25]

        per_level_metrics: list[dict] = []

        with torch.no_grad():
            original_01 = (original_tensor + 1.0) / 2.0
            orig_gray = original_01.squeeze(0).mean(dim=0).cpu().numpy()

            for sigma in noise_levels:
                noise = torch.randn_like(original_tensor) * sigma
                noisy = (original_tensor + noise).clamp(-1.0, 1.0)
                noisy_01 = ((noisy + 1.0) / 2.0).clamp(0.0, 1.0)

                # Reconstruct noisy image through VAE
                latent = self._vae.encode(noisy).latent_dist.mean
                recon = self._vae.decode(latent).sample
                recon_01 = ((recon + 1.0) / 2.0).clamp(0.0, 1.0)

                # MAE distances
                mae_noisy = float(torch.abs(original_01 - noisy_01).mean())
                mae_recon = float(torch.abs(original_01 - recon_01).mean())

                # LPIPS distances
                lpips_noisy = self._compute_lpips(original_01, noisy_01)
                lpips_recon = self._compute_lpips(original_01, recon_01)

                # SSIM (grayscale)
                noisy_gray = noisy_01.squeeze(0).mean(dim=0).cpu().numpy()
                recon_gray = recon_01.squeeze(0).mean(dim=0).cpu().numpy()
                ssim_noisy = self._compute_ssim(orig_gray, noisy_gray)
                ssim_recon = self._compute_ssim(orig_gray, recon_gray)

                # Snap-back coefficients per metric
                mae_coeff = (1.0 - mae_recon / mae_noisy) if mae_noisy > 1e-8 else 0.0
                lpips_coeff = (1.0 - lpips_recon / lpips_noisy) if lpips_noisy > 1e-8 else 0.0
                # SSIM gain: how much structural similarity improved
                ssim_gain = float(np.clip(ssim_recon - ssim_noisy, 0.0, 1.0))

                per_level_metrics.append({
                    "sigma": sigma,
                    "mae_coeff": round(mae_coeff, 4),
                    "lpips_coeff": round(lpips_coeff, 4),
                    "ssim_gain": round(ssim_gain, 4),
                })

        # Compute weighted score across levels
        if per_level_metrics:
            weighted_score = 0.0
            for m, w in zip(per_level_metrics, level_weights):
                # Per-level combined score: LPIPS is most discriminative
                level_score = (
                    m["mae_coeff"] * 0.30 +
                    m["lpips_coeff"] * 0.45 +
                    m["ssim_gain"] * 0.25
                )
                weighted_score += level_score * w

            # Normalize and map to probability
            # Empirical: real ~0.05-0.30, AI ~0.40-0.80
            score = float(np.clip((weighted_score - 0.15) / 0.50, 0.0, 1.0))
        else:
            score = 0.0

        # Legacy-compatible coefficients (MAE-based for evidence)
        coefficients = [m["mae_coeff"] for m in per_level_metrics]

        return {
            "snap_back_score": score,
            "coefficients": coefficients,
            "per_level_metrics": per_level_metrics,
        }

    @staticmethod
    def _laplacian_energy(gray: np.ndarray) -> float:
        """Approximate Laplacian energy (high-frequency content)."""
        # Simple 3×3 Laplacian kernel
        from scipy.ndimage import convolve
        kernel = np.array([[0, 1, 0],
                           [1, -4, 1],
                           [0, 1, 0]], dtype=np.float32)
        laplacian = convolve(gray, kernel, mode="reflect")
        return float(np.mean(laplacian ** 2))

    @staticmethod
    def _compute_lpips(img1: torch.Tensor, img2: torch.Tensor) -> float:
        """LPIPS-style perceptual distance using VGG16 features.

        Args:
            img1, img2: tensors in [0, 1] range, shape (1, 3, H, W)
        """
        vgg = _get_vgg_features()
        if vgg is None:
            return 0.0

        device = img1.device
        mean = torch.tensor([0.485, 0.456, 0.406], device=device).view(1, 3, 1, 1)
        std = torch.tensor([0.229, 0.224, 0.225], device=device).view(1, 3, 1, 1)
        with torch.no_grad():
            feat1 = vgg((img1 - mean) / std)
            feat2 = vgg((img2 - mean) / std)
        return float(torch.mean((feat1 - feat2) ** 2))

    @staticmethod
    def _compute_ssim(img1_np: np.ndarray, img2_np: np.ndarray) -> float:
        """Compute SSIM between two grayscale images in [0, 1] range."""
        from scipy.ndimage import uniform_filter
        C1 = 0.01 ** 2
        C2 = 0.03 ** 2
        mu1 = uniform_filter(img1_np, size=11)
        mu2 = uniform_filter(img2_np, size=11)
        sigma1_sq = uniform_filter(img1_np ** 2, size=11) - mu1 ** 2
        sigma2_sq = uniform_filter(img2_np ** 2, size=11) - mu2 ** 2
        sigma12 = uniform_filter(img1_np * img2_np, size=11) - mu1 * mu2
        num = (2 * mu1 * mu2 + C1) * (2 * sigma12 + C2)
        den = (mu1 ** 2 + mu2 ** 2 + C1) * (sigma1_sq + sigma2_sq + C2)
        ssim_map = num / den
        return float(ssim_map.mean())

    @staticmethod
    def _compute_fft_error_energy(error_gray: np.ndarray) -> dict:
        """Analyze FFT of error map — AI images concentrate error in mid frequencies."""
        fft = np.fft.fft2(error_gray)
        magnitude = np.abs(np.fft.fftshift(fft))
        h, w = magnitude.shape
        cy, cx = h // 2, w // 2
        Y, X = np.ogrid[:h, :w]
        r = np.sqrt((Y - cy) ** 2 + (X - cx) ** 2)
        r_max = min(cy, cx)
        total = magnitude.sum() + 1e-10
        low = float(magnitude[r < r_max * 0.33].sum() / total)
        mid = float(magnitude[(r >= r_max * 0.33) & (r < r_max * 0.66)].sum() / total)
        high = float(magnitude[r >= r_max * 0.66].sum() / total)
        return {"low": low, "mid": mid, "high": high}

    @staticmethod
    def _error_to_probability(
        mean_error: float,
        spatial_uniformity: float,
        high_freq_loss: float,
        fft_mid: float = 0.0,
    ) -> float:
        """
        Convert reconstruction error statistics to AI probability.

        Low mean_error = image is on VAE manifold = likely AI.
        High spatial_uniformity = error is evenly distributed = AI pattern.
        Low high_freq_loss = VAE preserves detail well = AI (native content).
        High fft_mid = error concentrated in mid frequencies = AI pattern.
        """
        # Error signal: lower error -> higher AI probability
        # Sigmoid-shaped mapping centred around _THRESH_SUSPECTED
        error_signal = 1.0 / (1.0 + np.exp(30.0 * (mean_error - 0.055)))

        # Uniformity signal: higher uniformity -> more likely AI
        uniform_signal = np.clip((spatial_uniformity - 0.40) / 0.40, 0.0, 1.0)

        # High-freq signal: lower loss (VAE preserves HF) -> more likely AI
        hf_signal = 1.0 - np.clip(high_freq_loss, 0.0, 1.0)

        # FFT signal: AI errors concentrate in mid frequencies
        fft_signal = float(np.clip((fft_mid - 0.15) / 0.30, 0.0, 1.0))

        # Weighted combination
        probability = (
            error_signal * 0.40 +
            uniform_signal * 0.25 +
            hf_signal * 0.15 +
            fft_signal * 0.20
        )

        return float(np.clip(probability, 0.0, 1.0))

    # ------------------------------------------------------------------
    # Findings
    # ------------------------------------------------------------------

    @staticmethod
    def _emit_findings(stats: dict, findings: list[AnalyzerFinding]) -> None:
        ai_prob = stats["ai_probability"]
        mean_err = stats["mean_error"]

        evidence = {
            "method": "vae_reconstruction_error",
            "vae_model": _VAE_MODEL_ID,
            **stats,
        }

        if ai_prob > 0.70:
            findings.append(
                AnalyzerFinding(
                    code="VAE_RECON_AI_DETECTED",
                    title="VAE rekonstrukcija indicira AI sadrzaj",
                    description=(
                        f"Stable Diffusion VAE rekonstrukcija pokazuje vrlo nisku "
                        f"gresku ({mean_err:.4f}), sto znaci da slika lezi na "
                        f"naucenom manifoldu VAE modela — tipicno za AI-generirane "
                        f"slike (rezultat: {ai_prob:.0%}). Prave fotografije imaju "
                        f"znacajno vecu rekonstrukcijsku gresku jer sadrze detalje "
                        f"koje VAE ne moze reproducirati."
                    ),
                    risk_score=min(0.95, max(0.70, ai_prob)),
                    confidence=min(0.92, 0.65 + ai_prob * 0.25),
                    evidence=evidence,
                )
            )
        elif ai_prob > 0.45:
            findings.append(
                AnalyzerFinding(
                    code="VAE_RECON_AI_SUSPECTED",
                    title="VAE rekonstrukcija — umjerena sumnja",
                    description=(
                        f"VAE rekonstrukcijska greska ({mean_err:.4f}) je niza od "
                        f"ocekivane za prirodne fotografije ({ai_prob:.0%} AI "
                        f"vjerojatnost). Moguce AI-generirani sadrzaj."
                    ),
                    risk_score=max(0.45, ai_prob * 0.90),
                    confidence=min(0.80, 0.50 + ai_prob * 0.25),
                    evidence=evidence,
                )
            )
        elif ai_prob > 0.25:
            findings.append(
                AnalyzerFinding(
                    code="VAE_RECON_AI_LOW",
                    title="VAE rekonstrukcija — blagi indikatori",
                    description=(
                        f"VAE rekonstrukcijska analiza pokazuje blage indikatore "
                        f"({ai_prob:.0%}) moguceg AI generiranja."
                    ),
                    risk_score=ai_prob * 0.60,
                    confidence=0.40 + ai_prob * 0.15,
                    evidence=evidence,
                )
            )
